version: '3.3'

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend.local

  service:
    env_file:
      - .env
    build: .
    volumes:
      - static_files_volume:/app/static
    networks:
      - my-network


  init:
    env_file:
      - .env
    build: .
    entrypoint: sh -c "python manage.py migrate"
    networks:
      - my-network
    depends_on:
      - postgres


  elastic:
    image: elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - el-data:/usr/share/elasticsearch/data

volumes:
  postgres-data:
  static_files_volume:
  el-data:
    driver: local

networks:
  backend.local:
    external: true
  my-network:
    external: true
